### ISSUE TITLE
2. Edit Order Items

### ISSUE THREAD

**Issue by MaggieChafee** [nss-evening-cohort-24/pos-system-panicroom#36]
# User Story
I, as a user, want to be able to edit the items that have already been added to a an order from the order details screen. 

# Acceptance Criteria
In order for this to work, I need the information that was previously submitted on the add item form to appear. The same form for adding an item will be used to edit the item. 

# Dependecies
The functionality of updating an item in an order depends on this step. 

# Dev Notes
In order for this step to function, I will need to:
- Event listener for addItem button (on view order details page)
- addItemForm – needs to populate menuItems
- Write selectItem() to create dropdown on form
- getMenuItems
- Form event: on submit, values are sent in payload to patch order object.
- updateOrder(payload)
- getSingleOrder then viewDetails

**Comment by cnfairall** [comment]
As a team we decided an edit order item functionality that would allow changing an item to a different item was redundant, and possibly confusing for the user. The user can add new items and delete ones they no longer need, which is more in line with an ecommerce experience. Therefore this issue will be closed without completion.
