### ISSUE TITLE
6 Decide on Git Organization

### ISSUE THREAD

**Issue by MaggieChafee** [nss-evening-cohort-24/pos-system-panicroom#8]
# User Story
Ensure all team members are aware of assignments and accountable for their contributions.

# Acceptance Criteria
Includes naming system for branches
2-person approval for pull requests
Folder layout and modularization
Assigning functionalities

# Dependencies
none

# Dev Notes
none

**Comment by cnfairall** [comment]
https://docs.google.com/document/d/1b9qvtgc1NxoyDdV3KoQJcsJ1vbNUZd2MXWIlVGjQD3Y/edit

divided functionalities to work on individually.
